apiVersion: v1
kind: Secret
metadata:
  name: carelink-secrets
  namespace: carelink
type: Opaque
data:
  Jwt__Key: zN3K9xY8s7FJk2lQvWmP4aR1T6uEoB5cXsfykmdu$&DJUSL9dHfG8JkL2pQ==
  RabbitMq__Password: Z3Vlc3Q=
  PayHere__Secret: eW91ci1wYXloZXJlLXNlY3JldA==
  PostgresPassword: YWRtaW4xMjM=
